### ISSUE TITLE
Which `flashrom` version is used?

### ISSUE THREAD

**Issue by danielsreichenbach** [3mdeb/pxe-server#28] opened 2018-09-29 12:52 UTC
Hi,

I've been trying to extend this project recently since we run a few APUs at work. One thing I stumbled over while trying to integrate the creation of root filesystem into a `Makefile` and automating it (to spare you the constant downloads :smile: ) is `flashrom`.

So far I found places mentioning I am supposed to build `flashrom`, others mention that on a system where it is packaged, one can just install the package.

My question: Which is correct?

- if we build, do we use the [forked version](https://github.com/pcengines/flashrom) or the [original version](https://github.com/flashrom/flashrom)?
- if we use the packaged version, is there any minimum version required for APU flashing to work?

**Comment by pietrushnic** [comment] 2018-10-01 09:52
@danielsreichenbach great you are interested in investing in this project.

Recently a lot happen behind the scene with `pxe-server`. If you take a look [here](https://github.com/3mdeb/pxe-server/pull/26) you can see we getting through major redesign. Things not going so smooth as I would expect it looks like mixing Docker, Ansible and VM cause some issues. Anyway I would like to have reproducible deployment environment for `pxe-server`. I started to write blog post with to express my ideas [here](https://github.com/3mdeb/news-and-ideas/pull/34/files).

Minimal version of `flashrom` that you should consider is `1.0.0`. Internally for RTE we use `meta-rte` Yocto layer which use [this receip](http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-bsp/flashrom/flashrom_1.0.bb?h=sumo). Please do not use fork it is rather for some customers that had special needs - mostly dirty hacks probably cannot be considered as upstream patches.

**Comment by danielsreichenbach** [comment] 2018-10-01 10:48
A simple suggestion for starters: have you looked at [netboot.xyz](https://github.com/antonym/netboot.xyz)?

This looks like it already is a decent starting point a rather broad deployment of PXE, and probably could be a replacement for what you tried to achieve in this repository.

My approach would be a little different:

- get rid of Ansible and VMs, and use only containers
- get rid of NFS, since you either TFTP boot into an iPXE environment or you already have one on the APU boards
- have a simple containerized nginx based PXE environment, pointing to a customized version of netboot.xyz

For bootstrapping:

- have containers for creating any bootstrapped Debian/Ubuntu/Xen (stable/LTS versions! Others are usually only fine for private use case)
- install supported `flashrom` and generated APU ROMs (latest supported version) into these environments

Finally:
- just use docker-compose to spin up a PXE environment with a TFTP and HTTP server, along with generated bootstrapped environments and actual PXE configuration

I would be happy to help with producing a reproducible environment :smile:

**Comment by pietrushnic** [comment] 2018-10-01 11:06
@danielsreichenbach thanks for pointing to `netboot.xyz` - yes it really looks like a better approach.

I'm glad I have some advisory from DevOps perspective and would be glad to have a conversation about things you mentioned:
* I need VM (Proxmox) since I can't have a separate box for `pxe-server`, maybe ansbiel + Docker is not the best idea, but I had no one to analyze review that approach. My problems: How to automate VM configuration and container deployment without Ansible (or something similar)? Even if I rely purely on the container I still have to build rootfs which fits my needs, shall I automate rootfs building with Dockerfile !?
* I'm not sure I understand NFS argument. It is not really TFTP boot, but HTTP boot I need customer kernels (Linux, Xen) and rootfs that can be shared across multiple kernels. I need one rtoofs for all testing environments. I don't want to have OS on apuX, truly I would like to test purely without any storage on platform so network boot is crucial.
* netboot.xyz is definitely something I have to consider it may solve most of my problems.

Maybe we should have a call to talk this through. Meanwhile, I really have to look at netboot.xyz.

**Comment by danielsreichenbach** [comment] 2018-10-01 11:55
I would recommend splitting the issues since provisioning and the VM to do so are different topics.

- Proxmox: have a dedicated repo that just provisions the VM using Ansible, since Ansible supports Proxmox just fine.
- NFS was a bit confusing since the current version exposes Debian root via NFS and I was not aware of having the external FS is the primary goal
- Regarding TFTP / HTTP: I get that APUs do not need TFTP since they can boot right of HTTP using iPXE.

What I'd also like to throw in: you could leverage TravisCI on Github to automate everything leading to the PXE environment too

We can have a call, shoot me an email and we'll arrange something.

**Comment by pietrushnic** [comment] 2022-10-06 12:33
We will have to move all effort to [Dasharo Tools Suite](https://docs.dasharo.com/common-coreboot-docs/dasharo_tools_suite/). I created new issue to continue: https://github.com/Dasharo/dasharo-issues/issues/217. 

I think key point here is to provide environment (DTS CE network booted) with flashrom version that has all necessary patches. DTS should be built through GH Actions (Travis CI is no longer free here) and automatically published at https://boot.3mdeb.com

So I'm closing this issue and we can continue in CI for DTS.

**Closed as completed by pietrushnic** 2022-10-06 12:33 UTC
